// @flow
export const CONDITION_MEMBERS = {
  HEIGHT: 'HEIGHT',
  WIDTH: 'WIDTH',
  BITRATE: 'BITRATE',
  FPS: 'FPS',
  ASPECTRATIO: 'ASPECTRATIO',
  INPUTSTREAM: 'INPUTSTREAM',
  LANGUAGE: 'LANGUAGE',
  CHANNELFORMAT: 'CHANNELFORMAT',
  CHANNELLAYOUT: 'CHANNELLAYOUT',
  STREAMCOUNT: 'STREAMCOUNT',
  AUDIOSTREAMCOUNT: 'AUDIOSTREAMCOUNT',
  VIDEOSTREAMCOUNT: 'VIDEOSTREAMCOUNT',
  DURATION: 'DURATION'
};

export const STREAM_CONDITION_MEMBERS = {
  BITRATE: 'BITRATE',
  CODEC: 'CODEC',
  FPS: 'FPS',
  HEIGHT: 'HEIGHT',
  WIDTH: 'WIDTH',
  MEDIA_TYPE: 'MEDIA_TYPE',
  STREAM_ID: 'STREAM_ID'
};

export const CONDITION_OPERATORS = {
  LESS_THAN_OR_EQUAL: '<=',
  LESS_THAN: '<',
  GREATER_THAN: '>',
  GREATER_THAN_OR_EQUAL: '>=',
  EQUAL: '==',
  UNEQUAL: '!='
};
